# Generated by Django 4.0.6 on 2022-07-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='blogpic/default.jpg', upload_to='profile/'),
        ),
    ]
