# Generated by Django 4.0.6 on 2022-07-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default='blogpic/default.jpg', upload_to='blogpic/'),
        ),
    ]
