# Generated by Django 4.0.6 on 2022-07-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comments_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_image',
            field=models.ImageField(default='blogpic/default.jpg', upload_to='commentpic/'),
        ),
    ]
