# Generated by Django 4.0.6 on 2022-07-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_categories_alter_comments_owner_blog_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='addcategory',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='addtag',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
