# Generated by Django 4.0.6 on 2022-07-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blog_addcategory_blog_addtag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='addtag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
