# Generated by Django 4.0.6 on 2022-07-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
        migrations.AddField(
            model_name='comments',
            name='reply_body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='reply_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
