# Generated by Django 4.0.6 on 2022-07-21 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_blog_slug_comments_reply_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='reply_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
