# Generated by Django 4.0.6 on 2022-07-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_blog_blog_image_alter_comments_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default='Tronicard.png', upload_to='blogpic/'),
        ),
    ]
