# Generated by Django 4.0.6 on 2022-07-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_blog_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default='Tronicard.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_image',
            field=models.ImageField(default='userimage.png', upload_to=''),
        ),
    ]
