# Generated by Django 4.0.6 on 2022-08-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_tags_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='blog',
            name='highlight',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
